#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
export PYTHONPATH="$(pwd)"

export MODEL_NAME="${MODEL_NAME:-Qwen/Qwen2.5-7B-Instruct}"
export VLLM_API_KEY="${VLLM_API_KEY:-local-dev-key}"
export VLLM_PORT="${VLLM_PORT:-8000}"

# GPU 1장: CUDA_VISIBLE_DEVICES=0 TENSOR_PARALLEL_SIZE=1
# GPU 2장: CUDA_VISIBLE_DEVICES=0,1 TENSOR_PARALLEL_SIZE=2
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-1}"
export PIPELINE_PARALLEL_SIZE="${PIPELINE_PARALLEL_SIZE:-1}"
export DISTRIBUTED_EXECUTOR_BACKEND="${DISTRIBUTED_EXECUTOR_BACKEND:-mp}"
export MAX_MODEL_LEN="${MAX_MODEL_LEN:-4096}"

python -m scripts.run_vllm
